### ISSUE TITLE
Schema discrepancies in Judgments

### ISSUE THREAD

**Issue by folbricht** [threatgrid/ctim#101]
- The documented schema for judgement requires `timestamp` but the stored objects only have `created`.
- Also, the stored objects have `owner` which isn't mentioned in schema documentation.

**Comment by yogsototh** [comment]
The question is how CTIM should describe its objects?

Because we could write documentation for stored entities instead of just new entities.

`timestamp` is part of `BaseEntity` and I'm not sure its meaning is the same as `created`.

So should we replace the documation of all entities by the documentation of their stored representation?

Should we simply add a new structure document describing the fields added on all entities once stored?

Should we get rid of `timestamp` in `BaseEntity` or should we provide a better description making it clear the semantic disctinction between `timestamp` and `created`.
Knowing `CTIM` should be agnostic of any running API. I'm not sure what is the best course of action.

**Comment by polygloton** [comment]
Sounds like we should just change the schemas that are used in the documentation to be the stored versions.
