### ISSUE TITLE
ctim-schema-version not in line with ctim version

### ISSUE THREAD

**Issue by yogsototh** [threatgrid/ctim#148]
The current ctim version is 0.4.7 but the variable ctim-schema-version is 0.4.3.

Perhaps we should write a script that take care of versionning upgrade, commits and tag to be certain to never forget these kind of details.

I believe the script in `release.sh` in another repo could be easily adapted.

Another solution would be to use `ctim-schema-version` as a prefix of ctim version to feel more coherent. For example using `ctim-schema-version=0.4.3` and ctim version `0.4.3-rcX`.

**Comment by polygloton** [comment]
My opinion is that we should only set the ctim-schema-version when we know there are schema changes.  This is because consumers of our data structures presumably won't know nor will they care when we release CTIM jars.  They only care if the schema is different from version to version.

I do advocate that, when we set a new schema version, it should match the CTIM version where the schema should changed.  So it might skip several versions.

It should be the duty of the person releasing CTIM to look at a diff (or the commits) since the last release and to determine then if the version needs to be updated.

**Comment by yogsototh** [comment]
My concern was about when reading the `schema-version` of some entity in ES. We'll have a version number that correspond to the `schema-version` but omit the real `ctim` version.

So there is some missing information there. I would rather prefer to have the following attitude:

- if the schema change, we update both ctim version and the schema version
- if the code change but not the schema we only update the ctim version in such a way that it is compatible with the schema version. For example schema-version = 0.4.3 and ctim-version = 0.4.3-2 (or any other suffix).
