### ISSUE TITLE
Investigate how we use nested documents in the sightings index

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctim#21]
We need to be judicious how we use nested documents for performance reasons.  Craig's asked us to review our current use of nested documents to represent observables within the sightings, to make sure it's the best approach.

**Comment by craigbro** [comment]
Nested objects are expensive in ES, and there is a default limit of 50 per document.  However, we need them to be able to search for Sightings by observable, since we want to specify the type and value of the observable, and the way to do this correctly is a nested object and nested query.  Otherwise we can match incorrectly on something like this:

:observables [{:type "file" :value "1.1.1.1"} {:ip "9.9.9.9"}]  when we ask for a IP of 1.1.1.1. with a simple compound query of:  'value:1.1.1.1 AND type:ip'

I am oing to suggest that we encode observables in a single `TYPE:VALUE` field that we generate at storage time in our ES backend.  This is NOT part of the StoredOBJECT schema, but it a generated field in the mapping only.  This way, we can search for observable_key:"ip:1.1.1.1" ..
