### ISSUE TITLE
Weakness model updates based on CWE data

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctim#212]
There are several updates to the weakness model that we should make, based on the contents of the CWE data.

### 1. Make `:modes_of_introduction :note` optional

I'm getting the error message: `"modes_of_introduction":[{"note":"missing-required-key"},{"note":"missing-required-key"}]` when trying to import a Weakness in local CTIA (master branch).

However, `note` is not a required key in the Weakness schema's `ModeOfIntroduction` map type: https://github.com/threatgrid/ctim/blob/18f5876bbd60b6496dd6341c6a1e6b836d3826cb/src/ctim/schemas/weakness.cljc#L21-L28

### 2. `:modes_of_introduction :note` should be Markdown

Many of the `<Modes_Of_Introduction><Note>` contents are arbitrarily nested XHTML, and need to be converted to Markdown strings.

https://github.com/threatgrid/ctim/blob/master/src/ctim/schemas/weakness.cljc#L26

### 3. `:detection_method :description` should be Markdown

Many of the `<Detection_Method><Description>` contents are XHTML, and need to be converted to Markdown strings.

https://github.com/threatgrid/ctim/blob/master/src/ctim/schemas/weakness.cljc#L110

**Comment by saintx** [comment]
This should be filed in CTIA.

**Comment by gbuisson** [comment]
In Flanders when you define a map entry it is set as required by default: 

https://github.com/threatgrid/flanders/blob/master/src/flanders/core.cljc#L18

Thus the `required?` here are superfluous, see the ModeOfIntroduction Object definition here: 

https://github.com/threatgrid/ctim/blob/18f5876bbd60b6496dd6341c6a1e6b836d3826cb/doc/structures/weakness.md#map8

So the code in CTIA works as designed, however the schema definition here is incorrect and needs to be changed on this repo, reopening the issue here and closing the CTIA one.

**Comment by gbuisson** [comment]
Changing the issue name so it accurately reflects the identified issue.
